### ISSUE TITLE
Solidus v4 compatibility?

### ISSUE THREAD

**Issue by arman-h** [solidusio-contrib/solidus_social#114]
Is this gem compatible with Solidus 4? According to the gemspec, it should be: `spec.add_dependency 'solidus_core', '>= 2.0.0', '< 5'`. But when trying to install either of the two most recent versions (`gem 'solidus_social', '~> 1.5'` or `gem 'solidus_social', '~> 1.4'`), there is an un-resolvable gem conflict:

```
Could not find compatible versions

Because solidus >= 4.0.1, < 4.1.0 depends on solidus_core = 4.0.1
  and solidus >= 4.0.0, < 4.0.1 depends on solidus_core = 4.0.0,
  solidus >= 4.0.0, < 4.1.0 requires solidus_core = 4.0.0 OR = 4.0.1.
And because solidus >= 4.1.0 depends on solidus_core = 4.1.0
  and solidus_social >= 1.4.0 depends on solidus_core >= 2.0.0, < 4,
  solidus_social >= 1.4.0 is incompatible with solidus >= 4.0.0.
So, because Gemfile depends on solidus ~> 4.0
  and Gemfile depends on solidus_social ~> 1.5,
  version solving has failed.
```

I was able to install the most current GitHub version using `gem 'solidus_social', github: 'solidusio-contrib/solidus_social'`, but then running `rails g solidus_social:install` throws an error:

```
/home/arman/.rvm/gems/ruby-3.1.3/bundler/gems/solidus_social-eb542f305243/app/decorators/controllers/solidus_social/spree/user_registrations_controller_decorator.rb:24:in `<module:UserRegistrationsControllerDecorator>': uninitialized constant Spree::UserRegistrationsController (NameError)

      ::Spree::UserRegistrationsController.prepend self
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Did you mean?  UserSessionsController
               UserConfirmationsController
```

**Comment by Jawad79Ahmad** [comment]
Also I'm getting same error

solidus_social-894abe233421/app/decorators/controllers/solidus_social/spree/user_registrations_controller_decorator.rb:24:in `<module:UserRegistrationsControllerDecorator>': uninitialized constant Spree::UserRegistrationsController (NameError)
Did you mean?  UserSessionsController
               UserConfirmationsController

**Comment by dtdionne** [comment]
Yeah, this error has been around for a while and remains out of the box with totally fresh installs.  It's perplexing and at the very least, self-defeating.  It halted me from even considering any financial support and caused me to resume evaluations...and that's unfortunate.

**Comment by dtdionne** [comment]
Yeah, sooooo uhhhh, my bad I think...this works fine with the depreciated frontend, at least it installs.

If that too suddenly quits working in the next 6 months we know the solidus folks are dishonest dirtbags trying to leverage "open source" for any other reason than its intent.

That may be a little harsh, forgive me but my guess is that the hosted solidus has all this stuff, but i dont know that.

**Comment by fthobe** [comment]
@jarednorman can be closed
