### ISSUE TITLE
::Spree::UserRegistrationsController.prepend self - not found on install

### ISSUE THREAD

**Issue by maykazw** [solidusio-contrib/solidus_social#115]
Hi, i want to add social register but I have problem with install this feature - can someone explain me, what m I doing wrong ?

`shop git:(main) ✗ bundle exec rails g solidus_social:install
/Users/maykazw/.rvm/gems/ruby-3.2.2/gems/solidus_social-1.6.0/app/decorators/controllers/solidus_social/spree/user_registrations_controller_decorator.rb:24:in <module:UserRegistrationsControllerDecorator>: uninitialized constant Spree::UserRegistrationsController (NameError)`
      ::Spree::UserRegistrationsController.prepend self
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`Did you mean?  UserSessionsController
               UserConfirmationsController
	from /Users/maykazw/.rvm/gems/ruby-3.2.2/gems/solidus_social-1.6.0/app/decorators/controllers/solidus_social/spree/user_registrations_controller_decorator.rb:5:in <module:Spree>
	from /Users/maykazw/.rvm/gems/ruby-3.2.2/gems/solidus_social-1.6.0/app/decorators/controllers/solidus_social/spree/user_registrations_controller_decorator.rb:4:in <module:SolidusSocial>
	from /Users/maykazw/.rvm/gems/ruby-3.2.2/gems/solidus_social-1.6.0/app/decorators/controllers/solidus_social/spree/user_registrations_controller_decorator.rb:3:in <main>
`

**Comment by kennyadsl** [comment]
Hello @maykazw, is this happening on a fresh install?

**Comment by thomasbromehead** [comment]
Hello @kennyadsl 
Having the same issue, in fact lots of ::Spree uninitialized constants in a lot of the solidus-contrib repos.
Tonight tried installing solidus_static_content and solidus_reviews and get the same problem, I will create an issue on each repo domani.
I'm on solidus 4.1.3, rails 7.0.8 and ruby 3.2.2
@maykazw Did you resolve this?

**Comment by kennyadsl** [comment]
Maybe it's already fixed by https://github.com/solidusio-contrib/solidus_social/pull/116? If you have a chance, can you please try and let me know if those are related?

**Comment by dtdionne** [comment]
I just did a fresh solidus install, worked great.  Then I tried to install social straight away and got the following similar error:

bundle exec rails g solidus_social:install
/usr/share/gems/gems/solidus_social-1.6.0/app/decorators/controllers/solidus_social/spree/user_registrations_controller_decorator.rb:24:in `<module:UserRegistrationsControllerDecorator>': uninitialized constant Spree::UserRegistrationsController (NameError)
Did you mean?  UserSessionsController
               UserConfirmationsController
	from /usr/share/gems/gems/solidus_social-1.6.0/app/decorators/controllers/solidus_social/spree/user_registrations_controller_decorator.rb:5:in `<module:Spree>'

**Comment by dtdionne** [comment]
Whats odd is I recall either this exact same error, or one so very similar back in sept in the prior version of SS.  A friend fixed it, that fix now appears in 1.6...but 1.6 is again broken, in this exact same place, but just in a different way.

**Comment by dtdionne** [comment]
Yeah, sooooo uhhhh, my bad I think...this works fine with the depreciated frontend, at least it installs.

If that too suddenly quits working in the next 6 months we know the solidus folks are dishonest dirtbags trying to leverage "open source" for any other reason than its intent.

**Comment by lucasfais** [comment]
I am facing this issue with a fresh solidus repo using starter frontend. I tested with both 1.6.0 and `master` branch. 

Any workarounds?

**Comment by fthobe** [comment]
@lucasfais Hey, did you manage to fix the issue?

**Comment by fthobe** [comment]
@jarednorman can be closed if #127 is merged

**Comment by fthobe** [comment]
@jarednorman can be closed
