### ISSUE TITLE
Error uninitialized constant OmniauthCallbacksController

### ISSUE THREAD

**Issue by Draiken** [solidusio-contrib/solidus_social#49]
I have been receiving this error since I installed solidus social but never been able to reproduce it.
My guess is that it's a very specific combination that triggers this, but nevertheless it keeps happening.

The error is:
```
NameError: uninitialized constant Spree::Admin::OmniauthCallbacksController
vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/inflector/methods.rb:271:in `const_get': uninitialized constant Spree::Admin::OmniauthCallbacksController (NameError)
    from vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/inflector/methods.rb:271:in `block in constantize'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/inflector/methods.rb:267:in `each'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/inflector/methods.rb:267:in `inject'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/inflector/methods.rb:267:in `constantize'
    from config/initializers/solidus_social.rb:46:in `block in <top (required)>'
    from vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:486:in `fail!'
    from vendor/bundle/ruby/2.4.0/gems/omniauth-oauth2-1.5.0/lib/omniauth/strategies/oauth2.rb:71:in `callback_phase'
    from vendor/bundle/ruby/2.4.0/gems/omniauth-facebook-5.0.0/lib/omniauth/strategies/facebook.rb:67:in `block in callback_phase'
    from vendor/bundle/ruby/2.4.0/gems/omniauth-facebook-5.0.0/lib/omniauth/strategies/facebook.rb:131:in `with_authorization_code!'
    from vendor/bundle/ruby/2.4.0/gems/omniauth-facebook-5.0.0/lib/omniauth/strategies/facebook.rb:66:in `callback_phase'
    from vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:236:in `callback_call'
    from vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:188:in `call!'
    from vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:168:in `call'
    from vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
    from vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
    from vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
    from vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/etag.rb:25:in `call'
    from vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/conditional_get.rb:25:in `call'
    from vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
    from vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232:in `context'
    from vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226:in `call'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/cookies.rb:613:in `call'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:97:in `run_callbacks'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
    from vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/rack/logger.rb:36:in `call_app'
    from vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/rack/logger.rb:24:in `block in call'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:69:in `block in tagged'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:26:in `tagged'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:69:in `tagged'
    from vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/rack/logger.rb:24:in `call'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/request_id.rb:25:in `call'
    from vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
    from vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/runtime.rb:22:in `call'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/executor.rb:12:in `call'
    from vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
    from vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/engine.rb:522:in `call'
    from vendor/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
    from vendor/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
    from vendor/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
    from vendor/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
    from vendor/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```
The request is pretty ordinary:
```
Referer: https://url/login
Url: /users/auth/facebook/callback?code=XXX&state=YYY
```

I have an unchanged version of the generated initializer. Only removed unused providers.

Any clues on what is happening and how I can fix this?

**Comment by jarednorman** [comment]
I notice that the initializer that the extension installs is pretty high up there in the stack trace.

```
from config/initializers/solidus_social.rb:46:in `block in <top (required)>'
```

Have you made any serious changes to that initializer, or is line 46 the same as it is [here](https://github.com/solidusio-contrib/solidus_social/blob/master/lib/generators/solidus_social/install/templates/config/initializers/solidus_social.rb#L46)?

**Comment by Draiken** [comment]
As I said on the description, no. It's the same exact initializer with commented out providers that I do not use.
Here, I uploaded it: https://gist.github.com/Draiken/cd73a2698dc28461bedcb8a8a9e4728d

**Comment by jarednorman** [comment]
Ah, sorry. I had just woken up. 😅 

This looks like it could be an annoying constant lookup issue. If `Spree::User` is the only devise model in your app, you could just hardcode the the callbacks controller and see if that works. Something like:

```ruby
OmniAuth.config.on_failure = proc do |env|
  env['devise.mapping'] = Devise.mappings[Spree.user_class.table_name.singularize.to_sym]
  Spree::OmniauthCallbacksController.action(:failure).call(env)
end
```

Alternatively, I'd add some logging or custom error reporting to that block to try and figure out why it's looking for the callbacks controller in `Spree::Admin`.

**Comment by Draiken** [comment]
I added some logging and I don't understand why this is wrong:
```
Mapping: {:sessions=>"spree/admin/user_sessions", :passwords=>"spree/admin/user_passwords", :omniauth_callbacks=>"spree/admin/omniauth_callbacks"}
Controller name is: Spree::Admin::OmniauthCallbacks
```
Searched my project and I don't set this anywhere. Either solidus_social or solidus_devise_auth must be setting this.

**Comment by jarednorman** [comment]
Yeah, that's really strange. Can you provide the versions of solidus/solidus_social/solidus_auth_devise you are using?

**Comment by Draiken** [comment]
```
  * solidus_api (2.6.0)
  * solidus_auth_devise (2.1.0)
  * solidus_backend (2.6.0)
  * solidus_core (2.6.0)
  * solidus_frontend (2.6.0)
  * solidus_social (1.2.0 eda0ffb)
```

**Comment by jarednorman** [comment]
Thanks. I'll try to take a look into this when I get the chance, though this is a pretty busy week for me so it might be a bit. Report back if you make any progress. 🙏

**Comment by Draiken** [comment]
I have used the proposed solution of calling the controller directly and it seems to be working.
For me at least, the issue is fixed. I would guess that some investigation would help sort if this is a real issue or something weird with my particular setup.

As I said, the only thing that led me to believe this is a gem issue was the fact that I hadn't customized anything on it.

Thanks a lot for the help anyways!

**Comment by pelargir** [comment]
We've been experiencing this problem as well. It stems from the `solidus_auth_devise` gem's `routes.rb` file which calls `#devise_for` twice: once for the frontend and once for the backend. The backend call to `#devise_for` is wrapped inside the admin namespace.

As documented in the Devise gem's `routes.rb` file, calling `#devise_for` from inside a namespace will automatically namespace any controllers used in the subsequent routes.

> by calling `devise_for` inside a namespace, it automatically nests your devise controllers

As a reuslt, when `solidus_social.rb` retrieves the `:ominauth_callbacks` controller below, it gets back a controller path prefixed with the admin namespace.

```
env['devise.mapping'] = Devise.mappings[Spree.user_class.table_name.singularize.to_sym]
controller_name  = ActiveSupport::Inflector.camelize(env['devise.mapping'].controllers[:omniauth_callbacks])
```

Then it tries to constantize this path:

```
controller_klass = ActiveSupport::Inflector.constantize("#{controller_name}Controller")
```

Resulting in the error @Draiken previously shared.

In fact, whatever value I pass to the controllers hash gets prefixed with spree/admin. I believe this is because `devise_for` was called last for the backend, so it overrides the frontend.

```
env['devise.mapping'].controllers[:omniauth_callbacks] # => spree/admin/omniauth_callbacks
env['devise.mapping'].controllers[:foo] # => spree/admin/foo
# etc.
```

This error can be reproduced consistently by attempting login to Solidus using a social media account, but instead of clicking "allow" when the social media site prompt appears, click "cancel" or equivalent. This results in the failure app being triggered.

I'm not sure how to fix this offhand.

**Comment by jarednorman** [comment]
@pelargir Thanks so much for digging in and finding the root cause of this one. We'll have to look at a way to un-namespace that if we can.
